ALTER TABLE patients
DROP CONSTRAINT IF EXISTS FK6JY7JJ1AKAKJUQS53OVILSDAD;

ALTER TABLE appointments
DROP CONSTRAINT IF EXISTS FK2QY49B66J7A055M24WBXKK74M;

ALTER TABLE patients
ADD CONSTRAINT FK_PATIENT_USER
FOREIGN KEY (id_user)
REFERENCES users(id_user)
ON DELETE SET NULL;

ALTER TABLE appointments
ADD CONSTRAINT FK_APPOINTMENTS_PATIENT
FOREIGN KEY (id_patient)
REFERENCES patients(id_patient)
ON DELETE CASCADE;